# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0002_productlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='available',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='unavailable', max_length=6),
        ),
        migrations.AddField(
            model_name='productlist',
            name='product_description',
            field=models.CharField(blank=True, default='ok', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productlist',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productlist',
            name='slug',
            field=models.SlugField(default='echo', max_length=40),
        ),
    ]
