# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0003_auto_20171101_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='available',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=6),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='product_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
