# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0004_auto_20171101_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='available',
            new_name='_available',
        ),
    ]
