# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0005_auto_20171101_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='_available',
            new_name='product_available',
        ),
    ]
