# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0007_auto_20171101_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='product_available',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=15),
        ),
    ]
