# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0009_auto_20171104_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='product_image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
