# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0010_auto_20171104_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlist',
            options={'ordering': ('-uploaded_at',)},
        ),
    ]
