# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0012_auto_20171104_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
