language: python
python:
- '2.7'
- '3.5'
env:
- DJANGO_VERSION=1.11.6
install:
- pip install -r requirements.txt
- pip install -q Django==$DJANGO_VERSION
before_install:
- openssl aes-256-cbc -K $encrypted_a385155268b0_key -iv $encrypted_a385155268b0_iv
  -in .env.enc -out .env -d
