language: python
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO_VERSION=1.11.6
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
before_script:
  - python manage.py migrate
script:
  - python manage.py test
