# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20171014_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
