# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20171014_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Phone',
            new_name='phone',
        ),
    ]
