# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20171018_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.IntegerField(default=-1),
        ),
    ]
