# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 13:59
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_profile_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=1, max_length=128),
            preserve_default=False,
        ),
    ]
