# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_client_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('view_Client', 'view_Client'),)},
        ),
    ]
