# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20171029_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
    ]
