# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20171029_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Senior', 'Senior Officer'), ('Junior', 'Junior Officer')], default='Choose Designation', max_length=20),
        ),
    ]
