# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20171112_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='Choose an option', max_length=6),
        ),
    ]
