# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20171112_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, upload_to='profile_pictures'),
        ),
    ]
