# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=b'In Progress', max_length=15),
        ),
    ]
