# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20171117_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'In Progress', b'In Progress'), (b'Done', b'Done'), (b'Rejected', b'Rejected')], default=b'In Progress', max_length=15),
        ),
    ]
