# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20171117_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updatedByManager',
            field=models.CharField(default='ashton', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updatedByManagerAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updatedByManagerId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
