# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20171117_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updatedByManagerId',
            field=models.IntegerField(null=True),
        ),
    ]
